imports:
    - { resource: controllers.yml }
    - { resource: audits.yml }

parameters:
    edgar.ezuiadit.param_converter.export.priority: 0

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIAudit\Handler\:
        resource: "../../../lib/Handler/*"
        public: true

    Edgar\EzUIAuditBundle\Cron\AuditExportCron:
        arguments:
            $kernelRootDir: "%kernel.root_dir%"
            $varDir: "$var_dir;ezsettings$"
            $storageDir: "$storage_dir$"
        tags:
            - { name: "edgar.cron", alias: "audit_export", priority: 100, expression: "*/5 * * * *" }

    Edgar\EzUIAuditBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzUIAudit\Form\Type\AuditTypeChoiceType: ~
